### PR TITLE
Fix/issues cleanup

### LINKED ISSUE #16: feat: build a set of tools for manipulating, creating and deleting ymal elements
build a set of tools for manipulating, creating and deleting yaml elements

It will help us to automate the creation of it

functions like add_one_datasource to the yaml etc...
 
remove datasource, add_one_metadata field etc

### PR DESCRIPTION
**Pull request by vladimirobucina**
Description: This PR is solving some issues in backlog. Such as:
- Adding new methods for yaml manipulation (`add_metadata`, `remove_metadata`, `add_datasource`, `remove_datasource`)
- Add `overwrite = TRUE` as default parameter for `write_cnt.dbi` function, to mimic `fs` behaviour.
- Fix some issues found in documentation.

Related issues: Closes #16, #19, #59 

Testing done: Added for new methods, updated for old ones.

Example code to run to test new methods: 

```{r}
# Example usage:

# Read the YAML file
test_config <- system.file("config", "default_config.yml", package = "connector")
file.copy(test_config, "test_config.yaml")

# Add metadata
config <- add_metadata("test_config.yaml", "new_metadata", "new_value")

# Remove metadata
config <- remove_metadata("test_config.yaml", "new_metadata")

# Add a new datasource
# Define the backend as a named list
new_backend <- list(
  type = "connector_jdbc",
  driver = "org.postgresql.Driver",
  url = "jdbc:postgresql://localhost:5432/mydatabase",
  user = "username",
  password = "password"
)

# Add a new datasource with the defined backend
config <- add_datasource("test_config.yaml", "new_datasource", new_backend)

# Remove a datasource
config <- remove_datasource("test_config.yaml", "new_datasource")

unlink("test_config.yaml")

```

Breaking changes: `ovewrite` parameter in `write_cnt` is a breaking change.

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -1,9 +1,10 @@
 Package: connector
 Title: Connect to your data easily
-Version: 0.0.4.9001
+Version: 0.0.5
```
Comment (akselthomsen) [inline DESCRIPTION:3]: Is the changes something we need to release internally right now?
Otherwise I would suggest keeping it as a dev version, and then implementing the new zephyr changes before next release.

File: R/utils_config.R
Comment (akselthomsen) [inline R/utils_config.R:1]: I think we should export these functions 😄 

Also when calling `read_file()` it should be with `eval.expr = FALSE`, so that expressions are not evaluated in the session changing the metadata, but instead when connecting.

File: vignettes/connector.Rmd
Comment (akselthomsen) [inline vignettes/connector.Rmd:1]: I get an error when rendering.
In the `yaml` block at line 63 it works if we remove the curly brackets, so rmarkdown is not looking for an yaml engine.

**Review by akselthomsen — CHANGES_REQUESTED** [review]
I really like the new functions to quickly manipulate config files 😄 
It's also in my comment, but I think they should be exported. Alternatively we could also create a `connector_config` class that uses these methods.

After my updates in zephyr we need to make the following small edit in `R/connect.R` when calling `zephyr:: report_checkmate_assertions` (ll. 337-341):

```R
  zephyr::report_checkmate_assertions(
    collection = val,
    message = "Invalid configuration file:",
    .envir = env
  )
```

File: DESCRIPTION (hunk 1 above)
Comment (vladimirobucina) [reply DESCRIPTION:3]: ok, I'll then just update dev version, I agree :)

File: R/utils_config.R
Comment (vladimirobucina) [reply R/utils_config.R:1]: ok, I just thought they will be used internally, I'll export them :)

File: vignettes/connector.Rmd
Comment (vladimirobucina) [reply vignettes/connector.Rmd:1]: I'll fix that

**Review by akselthomsen — APPROVED** [review]
